# .github/workflows/build-and-publish.yml
name: Build & Publish Wheels

on:
  push:
    tags:
      - 'v*'               # e.g. v0.1.5
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-vers: ['3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-vers }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-vers }}

      - name: Install build tools
        run: python -m pip install --upgrade pip setuptools wheel cibuildwheel

      - name: Build wheel
        env:
          CIBW_SKIP: 'pp*'      # skip PyPy
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          # no `name:` means “artifact is auto‑named”,
          # but you can give it one if you like.
          path: dist/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all built wheels
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*.whl
