name: Build & Publish Wheels

on:
  push:
    tags: ['v*']           # trigger on git tags like v0.1.5
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ['3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: python -m pip install --upgrade pip setuptools wheel cibuildwheel

      - name: Build wheel
        env:
          CIBW_SKIP: 'pp*'    # skip PyPy
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel-${{ matrix.os }}
          path: dist/*.whl

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # only on tagged commits
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download macOS wheel
        uses: actions/download-artifact@v2
        with:
          name: wheel-macos-latest
          path: dist

      - name: Download Windows wheel
        uses: actions/download-artifact@v2
        with:
          name: wheel-windows-latest
          path: dist

      - name: Install twine
        run: python -m pip install --upgrade twine

      - name: Publish wheels to PyPI
        run: twine upload dist/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN3 }}
