name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    env:
      # Skip PyPy builds
      CIBW_SKIP: "pp*"
      # Increase verbosity
      CIBW_BUILD_VERBOSITY: 1
      # Credentials for Twine
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          pip install --upgrade pip
          pip install cibuildwheel==2.15.0 twine

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

      - name: List built wheels
        run: ls dist

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          python -m twine upload dist/*.whl
