name: Build & Publish Wheels

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-vers: ['3.13']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-vers }}

      - run: python -m pip install --upgrade pip setuptools wheel cibuildwheel

      - name: Build wheel
        env:
          CIBW_SKIP: 'pp*'
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2    # <-- switch to @v2
        with:
          path: dist/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Download built wheels
        uses: actions/download-artifact@v2  # <-- switch to @v2
        with:
          path: dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*.whl
