name: Build & Publish Wheels

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-vers: ['3.9','3.10','3.11','3.12','3.13']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-vers }}

      - name: Install build tools
        run: python -m pip install --upgrade pip setuptools wheel cibuildwheel

      - name: Build wheels
        env:
          CIBW_SKIP: 'pp*'
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-vers }}
          path: dist/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Publish all wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN3 }}
        run: twine upload dist/*.whl
