name: Test Artifact

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create a file
        run: echo "hello" > hello.txt

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: hello.txt

          